#!/bin/bash

source ${MODULESHOME}/init/bash
module load intel
module load openfoam/boost/intel/1.57.0
module load openfoam/cgal/intel/4.6.1
module load openfoam/gmp/intel/6.0.0
module load openfoam/mpfr/intel/3.1.2
module load openfoam/parmgridgen/intel/1.0
module load openfoam/zlib/intel/1.2.8
module load openfoam/flex/intel/2.5.39
module load openfoam/metis/intel/5.1.0
module load openfoam/parmetis/intel/4.0.3
module load openfoam/openmpi/intel/1.6.5
module load openfoam/scotch/intel/6.0.4

source settings.sh

NAME="OpenFOAM"
VERSION="dev"
LABEL="intel"

ARCHIVE_PREFIX="${NAME}-${VERSION}"

BUILD_PATH="${ROOT_DIR}/${ARCHIVE_PREFIX}"

cd $BUILD_PATH

export FOAM_INST_DIR=${ROOT_DIR}
source etc/bashrc WM_COMPILER=Icc WM_NCOMPPROCS=${CORES}
./Allwmake

